version: '3.8'

services:
  rpi-core:
    build: .
    image: rpi-core:latest
    container_name: rpi-core
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"